server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
    fetch-registry: false
    register-with-eureka: false

security:
  basic:
    enabled: true
  user:
    name: root
    password: ok
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_user
    username: root
    password: ok